spring.application.name=backend

server.port=${PORT:8080}

file.upload.tempDir=./temp_uploads
file.upload.tempExpirationMinutes=30

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Session cookie for cross-site usage (Netlify -> Render)
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=None