spring.application.name=backend
server.port=8081
file.upload.tempDir=./temp_uploads
file.upload.tempExpirationMinutes=30

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB